name: Deploy to prod
on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t burger-restaurant-backend .

    - name: SSH to VPS and deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker stop burger-restaurant-backend || true
          docker rm burger-restaurant-backend || true
          docker run -d --name burger-restaurant-backend -p 4000:4000 burger-restaurant-backend