FROM node:20-alpine

RUN apt-get update -y
RUN apt-get install -y openssl
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma

RUN npx prisma generate

COPY . .

RUN node build.js

EXPOSE 7000

CMD ["node", "dist/index.js"]