FROM node:20-alpine

RUN apk update && apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma

RUN npx prisma generate

COPY . .

RUN node build.js

EXPOSE 7000

CMD ["node", "dist/index.js"]