version: "3.9"
services:
  myapp-router:
    image: alpine/socat
    container_name: router
    restart: always
    networks:
      - app_net
    command: TCP-LISTEN:${API_PORT},fork,reuseaddr TCP:${TARGET_CONTAINER}:${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"

networks:
  burger_restaurant_net:
    external: true