services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    network_mode: bridge 
    ports:
      - "7000:7000"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped 
  
  swagger:
    build:
      context: .
      dockerfile: Dockerfile.swagger
    container_name: swagger
    network_mode: bridge
    ports:
      - "7001:7001"
    env_file:
      - .envSwagger
    volumes:
      - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped 


