services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        APP_PORT: ${API_PORT}
    container_name: backend
    network_mode: bridge 
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped 
  
  swagger:
    build:
      context: .
      dockerfile: Dockerfile.swagger
      args:
        APP_PORT: ${SWAGGER_PORT}
    container_name: swagger
    network_mode: bridge
    ports:
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    env_file:
      - .envSwagger
    volumes:
      - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped 


