services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    network_mode: bridge 
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped 

