version: '3'
services:
  app:
    image: burger-restaurant-backend
    build: .
    ports:
      - "4000:4000"
    environment:
      - SECRET_AUTH_TOKEN=${{ secrets.SECRET_AUTH_TOKEN }}
      - DATABASE_URL=${{ secrets.DATABASE_URL }}