version: "3.9"
services:
  nginx-router:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - API_PORT
      - SWAGGER_PORT
    networks:
      - prod_burger_network
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

networks:
  prod_burger_network:
    external: true
