- name: Clean up unnecessary containers and images
  hosts: web1
  become: yes
  vars:
    image_prefix: "{{ lookup('env','DOCKER_IMAGE_PREFIX') }}"
    image_server_prefix: "{{ lookup('env','DOCKER_IMAGE_SERVER_PREFIX') }}"
    container_router_name: "{{ lookup('env','DOCKER_ROUTER_CONTAINER_NAME') }}"

  tasks:
    - include_tasks: tasks/get_blue_data.yml
      vars:
        container_router_name: "{{ router_name }}"  

    - name: Show the IP of the blue container
      debug:
        msg: "{{ blue_ip }}"

    - name: Show the hash of the blue image/container
      debug:
        msg: "{{ blue_sha }}"

    - name: Clean unecessary containers
      shell: |
        docker ps -a --format "{{ "{{.ID}} {{.Image}}" }}" \
        | grep "{{image_prefix}}{{image_server_prefix}}" \
        | grep -v "{{ blue_sha }}" \
        | awk '{print $1}' \
        | xargs -r docker rm -f
      ignore_errors: true
      register: containers_cleanup_result

    - name: Show the result of containers cleanup
      debug:
        msg: "{{ containers_cleanup_result.stdout }}"

    - name: Clean unecessary images
      shell: |
        docker images --format "{{ "{{.ID}} {{.Repository}}" }}" \ \
        | grep "{{image_prefix}}{{image_server_prefix}}" \
        | grep -v "{{ blue_sha }}" \
        | awk '{print $1}' \
        | xargs -r docker rmi -f
      ignore_errors: true
      register: images_cleanup_result

    - name: Show the result of images cleanup
      debug:
        msg: "{{ images_cleanup_result.stdout }}"
