- name: Prepare environment
  hosts: web1
  become: yes
  vars:
    image_prefix: "{{ lookup('env','DOCKER_IMAGE_PREFIX') }}"

  tasks:
    - name: Check if Docker is installed 
      block:
      - name: Try to run docker command
        command: docker --version
        register: docker_version
        ignore_errors: true
        failed_when: false

      - name: Show the variable
        debug:
          msg: "Docker installed: {{ docker_version.rc == 0 }}"

    - name: Install Docker
      shell: |
        if [ {{ docker_version.rc }} -ne 0 ]; then
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          usermod -aG docker {{ ansible_user }}
        fi

    - name: Check if Docker Compose is installed 
      block:
      - name: Try to run docker compose command
        command: docker compose version
        register: docker_compose_version
        ignore_errors: true
        failed_when: false

      - name: Show the variable
        debug:
          msg: "Docker Compose installed: {{ docker_compose_version.rc == 0 }}"

    - name: Install Docker Compose
      shell: |
        if [ {{ docker_compose_version.rc }} -ne 0 ]; then
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
        fi

    
    # - name: Get active backend hash from router
    #   shell: |
    #     docker inspect router \
    #       --format '{{ "{{range .Config.Env}}{{println .}}{{end}}" }}' \
    #       | grep TARGET_CONTAINER || echo "" \
    #       | cut -d'=' -f2 \
    #       | sed 's/backend-//'
    #   register: router_hash
    #   ignore_errors: true

    - name: C11
      shell: docker ps -a 
      register: docker_ps

    - name: Debug 1
      debug:
        msg: "aaa: {{  docker_ps.stdout }}"

    - name: c22
      shell: docker ps -a 
      register: docker_ps

    - name: Debug 2
      debug:
        msg: "bbb: {{image_prefix}}"

    - name: Clean unecessary containers
      shell: |
        docker ps -a  \
        | grep "{{image_prefix}}" \
        | awk '{print $1}' \
        | xargs -r docker rm -f
      ignore_errors: true


    - name: Clean unecessary images
      shell: |
        docker images \
        | grep "{{image_prefix}}" \
        | awk '{print $1}' \
        | xargs -r docker rm -f
      ignore_errors: true

  #  | grep -v "{{ router_hash.stdout | default('') }}" \
        # | grep -v "{{ router_hash.stdout | default('') }}" \
