- name: Build Servers
  hosts: web1
  become: yes
  vars:
    domain_name: "{{ lookup('env','DOMAIN_NAME') }}"
    server_build_path: "/var/www/{{ domain_name }}"
    secret_auth_token: "{{ lookup('env','SECRET_AUTH_TOKEN') }}"
    database_url: "{{ lookup('env','DATABASE_URL') }}"
    api_port: "{{lookup('env','API_PORT') }}"
    swagger_port: "{{lookup('env','SWAGGER_PORT') }}"
    swagger_name: "{{ lookup('env','DOCKER_SWAGGER_NAME') }}"
    backend_name: "{{ lookup('env','DOCKER_BACKEND_NAME') }}"
    current_sha: "{{ lookup('env','CURRENT_SHA') }}"
    network_name: "prod_burger_network"
    image_prefix: "{{ lookup('env','DOCKER_IMAGE_PREFIX') }}"
    server_prefix: "{{ lookup('env','DOCKER_IMAGE_SERVER_PREFIX') }}"

    
  tasks:
    - include_tasks: tasks/get_blue_data.yml

    - name: Create .env file
      copy:
        content: |
          SECRET_AUTH_TOKEN={{ secret_auth_token }}
          DATABASE_URL={{ database_url }}
          API_PORT={{ api_port }}
          CURRENT_SHA={{ current_sha }}
        dest: "{{ server_build_path }}/.env"
        mode: "0600"

    - name: Create .envSwagger file
      copy:
        content: |
          SWAGGER_PORT={{ swagger_port }}
        dest: "{{ server_build_path }}/.envSwagger"
        mode: "0600"

    - name: Create Docker network
      shell: |
        docker network inspect {{ network_name }} >/dev/null 2>&1 || docker network create {{ network_name }}

    - name: Run Docker Compose
      shell: |
        cd {{ server_build_path }}
        CURRENT_SHA={{ current_sha }} \
        API_PORT={{ api_port }} \
        SWAGGER_PORT={{ swagger_port }} \
        SWAGGER_CONTAINER_NAME={{ swagger_name }} \
        BACKEND_CONTAINER_NAME={{ backend_name }} \
        docker compose -p {{ image_prefix }}{{ server_prefix }}{{ current_sha }} up -d --build --remove-orphans
      
    - name: Create version.env file
      copy:
        content: |
          PREV_STABLE={{ blue_sha }}
          NEW={{ current_sha }}
        dest: "{{ server_build_path }}/version.env"
        mode: "0600"

