name: Deploy

on:
  pull_request:
    types: [opened, reopened, synchronize] 

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      CERTBOT_EMAIL: ${{ secrets.CERTBOT_EMAIL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_AUTH_TOKEN: ${{secrets.SECRET_AUTH_TOKEN}}
      API_PORT: ${{ vars.API_PORT }}
      SWAGGER_PORT: ${{ vars.SWAGGER_PORT }}
      DOCKER_IMAGE_PREFIX: "prod-burger-"
      DOCKER_IMAGE_SERVER_PREFIX: "server-"
      DOCKER_ROUTER_CONTAINER_NAME: "burger-router"
      DOCKER_BACKEND_NAME: "backend"
      DOCKER_SWAGGER_NAME: "swagger"
      VERSION_FILE_NAME: "version.env"
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set SHA
        run: echo "CURRENT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H $SERVER_IP  >> ~/.ssh/known_hosts

      - name: Run Ansible [Upload to server]
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook_upload.yml
      
      - name: Run Ansible [Prepare environment]
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook_prepare_environment.yml

      - name: Run Ansible [Clean up unnecessary containers and images]
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook_cleanup_docker.yml

      - name: Run Ansible [Build servers]
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook_build.yml

      - name: Run Ansible [Routing]
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook_router.yml

      - name: Run Ansible [Configure Nginx]
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook_nginx.yml
