name: 🚀 Manual Deploy

on:
  workflow_dispatch:
    inputs:
      target_sha:
        description: 'SHA'
        required: false
        type: string
      environment:
        description: 'production'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      CERTBOT_EMAIL: ${{ secrets.CERTBOT_EMAIL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_AUTH_TOKEN: ${{secrets.SECRET_AUTH_TOKEN}}
      API_PORT: ${{ vars.API_PORT }}
      SWAGGER_PORT: ${{ vars.SWAGGER_PORT }}
      DOCKER_IMAGE_PREFIX: "prod-burger-"
      DOCKER_IMAGE_SERVER_PREFIX: "server-"
  
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target_sha || github.ref }}

      - name: 🔢 Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: 🔑 Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 📡 Add server to known_hosts
        run: ssh-keyscan -H $SERVER_IP  >> ~/.ssh/known_hosts