name: Switch blue/green

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Switch to version:'
        required: true
        type: choice
        options:
          - new
          - stable

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      VERSION_FILE_NAME: "version.env"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ansible [Switch version]
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook_switch_version.yml -e "apply_version=${{ github.event.inputs.action }}"